# Generated by Django 2.1.1 on 2019-02-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
