# Generated by Django 2.1.1 on 2019-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190202_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.CharField(default='Paid vacation', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='company_overview',
            field=models.CharField(default='enter company overview', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.CharField(default='job description', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Miami', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.CharField(default='qualifications', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.CharField(default='job responsibilities', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='salary info', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='job skills', max_length=200),
        ),
    ]
