# Generated by Django 2.1.1 on 2019-02-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190202_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=100)),
                ('telephone', models.IntegerField(default='')),
                ('street_address1', models.CharField(default='', max_length=100)),
                ('street_address_2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=70)),
                ('state', models.CharField(default='', max_length=70)),
                ('zip_code', models.IntegerField(default='')),
                ('password', models.CharField(default='', max_length=10)),
                ('job_title_1', models.CharField(default='', max_length=100)),
                ('company_name_1', models.CharField(default='', max_length=100)),
                ('company_city_1', models.CharField(default='', max_length=70)),
                ('job_start_month_1', models.CharField(default='', max_length=20)),
                ('job_start_year_1', models.IntegerField(default='')),
                ('job_end_month_1', models.CharField(default='', max_length=20)),
                ('job_end_year_1', models.IntegerField(default='')),
                ('job_description_1', models.CharField(default='', max_length=200)),
                ('qualification_1', models.CharField(default='', max_length=70)),
                ('degree_1', models.CharField(default='', max_length=70)),
                ('school_name_1', models.CharField(default='', max_length=70)),
                ('field_of_study_1', models.CharField(default='', max_length=70)),
                ('school_city_1', models.CharField(default='', max_length=70)),
                ('school_start_month_1', models.CharField(default='', max_length=70)),
                ('school_start_year_1', models.IntegerField(default='')),
                ('school_end_month_1', models.CharField(default='', max_length=70)),
                ('school_end_year_1', models.CharField(default='', max_length=5)),
                ('skills', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
