# Generated by Django 2.1.1 on 2019-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190206_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlToImage', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_location',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Miami', max_length=50),
        ),
    ]
