# Generated by Django 2.1.1 on 2019-02-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190206_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='company_location',
        ),
    ]
